# fly.toml app configuration file generated for mudai-backend on 2026-04-28T10:55:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mudai-backend'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpus = 4
  memory_mb = 2048
